// Seasoned fixtures
window.fixturesBySeason = {
  "1": [
    {A:"Will",B:"Luke",Ascore:14,Bscore:16,Winner:"Luke",Week:"Week 1"},
    {A:"James",B:"Mitch",Ascore:6,Bscore:11,Winner:"Mitch",Week:"Week 1"},
    {A:"Jordan",B:"Will",Ascore:11,Bscore:5,Winner:"Jordan",Week:"Week 1"},
    {A:"Luke",B:"James",Ascore:5,Bscore:11,Winner:"James",Week:"Week 1"},
    {A:"Mitch",B:"Jordan",Ascore:11,Bscore:9,Winner:"Mitch",Week:"Week 1"},
    {A:"Will",B:"James",Ascore:7,Bscore:11,Winner:"James",Week:"Week 1"},
    {A:"Jordan",B:"Luke",Ascore:11,Bscore:8,Winner:"Jordan",Week:"Week 1"},
    {A:"Mitch",B:"Will",Ascore:11,Bscore:8,Winner:"Mitch",Week:"Week 1"},
    {A:"James",B:"Jordan",Ascore:3,Bscore:11,Winner:"Jordan",Week:"Week 1"},
    {A:"Luke",B:"Mitch",Ascore:9,Bscore:11,Winner:"Mitch",Week:"Week 1"},
    {A:"Will",B:"Kepp",Ascore:21,Bscore:18,Winner:"Will",Week:"Week 2"},
    {A:"Luke",B:"Jordan",Ascore:12,Bscore:21,Winner:"Jordan",Week:"Week 2"},
    {A:"James",B:"Mitch",Ascore:18,Bscore:21,Winner:"Mitch",Week:"Week 2"},
    {A:"Kepp",B:"Luke",Ascore:19,Bscore:21,Winner:"Luke",Week:"Week 2"},
    {A:"Will",B:"Jordan",Ascore:12,Bscore:21,Winner:"Jordan",Week:"Week 2"},
    {A:"James",B:"Kepp",Ascore:21,Bscore:16,Winner:"James",Week:"Week 2"},
    {A:"Mitch",B:"Luke",Ascore:21,Bscore:10,Winner:"Mitch",Week:"Week 2"},
    {A:"Jordan",B:"Kepp",Ascore:21,Bscore:8,Winner:"Jordan",Week:"Week 2"},
    {A:"Will",B:"James",Ascore:17,Bscore:21,Winner:"James",Week:"Week 2"},
    {A:"Mitch",B:"Jordan",Ascore:21,Bscore:14,Winner:"Mitch",Week:"Week 2"},
    {A:"Luke",B:"James",Ascore:22,Bscore:24,Winner:"James",Week:"Week 2"},
    {A:"Will",B:"Mitch",Ascore:17,Bscore:21,Winner:"Mitch",Week:"Week 2"},
    {A:"Jordan",B:"James",Ascore:21,Bscore:17,Winner:"Jordan",Week:"Week 2"},
    {A:"Kepp",B:"Mitch",Ascore:15,Bscore:21,Winner:"Mitch",Week:"Week 2"},
    {A:"Will",B:"Luke",Ascore:18,Bscore:21,Winner:"Luke",Week:"Week 2"},
    {A:"Will",B:"James",Ascore:13,Bscore:21,Winner:"James",Week:"Week 3"},
    {A:"Kepp",B:"Jordan",Ascore:13,Bscore:21,Winner:"Jordan",Week:"Week 3"},
    {A:"Kepp",B:"Will",Ascore:19,Bscore:21,Winner:"Will",Week:"Week 3"},
    {A:"Jordan",B:"Luke",Ascore:21,Bscore:19,Winner:"Jordan",Week:"Week 3"},
    {A:"Kepp",B:"Kath",Ascore:15,Bscore:21,Winner:"Kath",Week:"Week 3"},
    {A:"James",B:"Luke",Ascore:6,Bscore:21,Winner:"Luke",Week:"Week 3"},
    {A:"Kath",B:"Luke",Ascore:16,Bscore:21,Winner:"Luke",Week:"Week 3"},
    {A:"James",B:"Jordan",Ascore:19,Bscore:21,Winner:"Jordan",Week:"Week 3"},
    {A:"Kepp",B:"Luke",Ascore:21,Bscore:14,Winner:"Kepp",Week:"Week 4"},
    {A:"Will",B:"Sam",Ascore:21,Bscore:18,Winner:"Will",Week:"Week 4"},
    {A:"Jordan",B:"James",Ascore:21,Bscore:15,Winner:"Jordan",Week:"Week 4"},
    {A:"Sam",B:"Kepp",Ascore:21,Bscore:14,Winner:"Sam",Week:"Week 4"},
    {A:"Jordan",B:"Will",Ascore:21,Bscore:10,Winner:"Jordan",Week:"Week 4"},
    {A:"James",B:"Luke",Ascore:20,Bscore:22,Winner:"Luke",Week:"Week 4"},
    {A:"Jordan",B:"Sam",Ascore:19,Bscore:21,Winner:"Sam",Week:"Week 4"},
    {A:"Kepp",B:"Will",Ascore:21,Bscore:6,Winner:"Kepp",Week:"Week 4"},
    {A:"James",B:"Kepp",Ascore:21,Bscore:17,Winner:"James",Week:"Week 4"},
    {A:"Luke",B:"Sam",Ascore:20,Bscore:22,Winner:"Sam",Week:"Week 4"},
    {A:"Kepp",B:"Jordan",Ascore:18,Bscore:21,Winner:"Jordan",Week:"Week 4"},
    {A:"Luke",B:"Will",Ascore:21,Bscore:10,Winner:"Luke",Week:"Week 4"}
  ],
  "2": [] // future
};

// Player profiles
window.playerProfiles = {
  "Mitch": {hand:"Right",height:"1.75m",age:32,racket:"Yonex Astrox 88D",image:"images/mitch.png",status:"injured"},
  "Luke":  {hand:"Left",height:"1.749m",age:29,racket:"Yonex Nanoflare 001",image:"images/luke.png"},
  "James": {hand:"Right",height:"1.79m",age:27,racket:"Yonex Arcsaber 11",image:"images/james.png"},
  "Will":  {hand:"Right",height:"1.74m",age:27,racket:"Yonex Nanoflare 700",image:"images/will.png"},
  "Jordan":{hand:"Right",height:"1.82m",age:29,racket:"Li-Ning Halbertec 2000",image:"images/jordan.png"},
  "Kepp":  {hand:"Right",height:"1.87m",age:27,racket:"Yonex Racket",image:"images/kepp.png"},
  "Sam":   {hand:"Right",height:"1.80m",age:30,racket:"Carlton Kinesis X1",image:"images/sam.png"},
  "Kath":  {hand:"Right",height:"1.20m",age:27,racket:"Yonex Racket",image:"images/kath.png"}
};
